version: '3.0'
services:
    cassandra:
        image: cassandra
        ports: 
            - '9042:9042'
    zookeeper:
        image: confluentinc/cp-zookeeper
        ports: 
            - '2181:2181'
        environment: 
            - ZOOKEEPER_CLIENT_PORT=2181
        depends_on: 
            - cassandra
    broker:
        image: confluentinc/cp-kafka
        environment: 
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://192.168.0.106:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
            - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
            - KAFKA_JMX_PORT=9101
        depends_on: 
            - zookeeper
        ports:
          - "29092:29092"
          - "9092:9092"
          - "9101:9101"